### ISSUE TITLE
Great work! Can I know if there is any implementation or script to call this model? Thanks.

### ISSUE THREAD

**Issue by WilTay1** [llava-rlhf/LLaVA-RLHF#1]

**Comment by Edward-Sun** [comment]
Hi, thanks for you interest in our work. We are still working on code cleaning.

For now, you can install the [LLaVA](https://github.com/haotian-liu/LLaVA) repo and use [this gist](https://gist.github.com/Edward-Sun/33227c5955a4018827138198a59894fb) to replace the `model/builder.py` file in llava.

Then, you can call the LLaVA-RLHF model by:

```python
load_bf16 = True

tokenizer, model, image_processor, context_len = load_pretrained_model(
    model_path, None, model_name, load_bf16=load_bf16)

model = PeftModel.from_pretrained(
      model,
      lora_path,
)
```

And remember to convert the input image to `torch.bfloat16`

```
images = images.to(dtype=torch.bfloat16)
```

**Comment by barshag** [comment]
So  after replacing the gist, it will work straight-forward with the GRADIO?
