### ISSUE TITLE
where is LLaVA-Fact-RM-13b-v1.5-336-lora-padding/checkpoint-200? 

### ISSUE THREAD

**Issue by HarrySSH** [llava-rlhf/LLaVA-RLHF#10]
In the fine tuning bash script, 
you mention a directory "LLaVA-Fact-RM-13b-v1.5-336-lora-padding/checkpoint-200" 

but it is unclear how you get that checkpoint from where, is it a checkpoint we computed ourselves? how?
wondering if you could provide more details on that. thanks

**Comment by Edward-Sun** [comment]
Hi Harry,

Ideally, this is the checkpoint you will get after running `bash scripts/13b-v1.5-336/train_reward_model.sh`

You can also use our provided checkpoint at the [hugging face hub](https://huggingface.co/zhiqings/LLaVA-RLHF-13b-v1.5-336/tree/main/rm_lora_adapter_model).
