### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Fake10086** [llava-rlhf/LLaVA-RLHF#15]

**Comment by Fake10086** [comment]
Can you provide a url for downloading vicuna-v1.5 mm_projector weight, because I didn't find it on the official LLaVA repository.

**Comment by Edward-Sun** [comment]
Hi Ji,

Do you need the mm_projector weight after pre-training or SFT? For SFT, I believe the weight is already in the released [model weight](https://huggingface.co/zhiqings/LLaVA-RLHF-7b-v1.5-224/tree/main/sft_model), you can use `torch.load` to find the exact weight if you need it.

**Comment by Fake10086** [comment]
I need the weight after pre-training.

**Comment by Fake10086** [comment]
I only found vicuna-1.5 used for LLaVA-1.5, and its mm_projector is a 2 layer MLP.

**Comment by sIncerass** [comment]
Hi there, you can use [7b](https://drive.google.com/drive/folders/1Wx4IZqTzDxVpxGWH0Zdd6xlLjDjvXdHU?usp=sharing) and [13b](https://drive.google.com/drive/folders/1rk4IMjQjv9NAiZNDXpM1HCifAIYGA_bf?usp=sharing).

**Comment by Fake10086** [comment]
Thanks!
