### ISSUE TITLE
Question about insrtuction data

### ISSUE THREAD

**Issue by zhang-jr** [llava-rlhf/LLaVA-RLHF#17]
Thanks for your great work!

I'm just curious, is it appropriate to blend your data with other instruction data like llava-instruction and svit for training in one phase, or is it suitable to train them separately? 

I have read the data filtering strategy in section 3.7 of your paper. Have you considered conducting experiments with other data blending and sampling techniques?

**Comment by Edward-Sun** [comment]
Hi, for the supervised fine-tuning stage, I believe blending our data (vqav2 + oakvqa + flicker + llava subset-5k) with other data (like those new data in llava-1.5) is better than training them separately.

As for the data filtering strategy, we don't have considered blending configurations other than what we have reported in the paper.
