### ISSUE TITLE
how can I find the eval_image files while evaluating the llava bench?

### ISSUE THREAD

**Issue by Amanda2024** [llava-rlhf/LLaVA-RLHF#21]
hi, while evaluation, the eval_image is missing

**Comment by Edward-Sun** [comment]
Hi @Amanda2024 , the eval_image are from coco and the questions are from [here](https://github.com/haotian-liu/LLaVA/tree/be683a6884bb663f870995e95211ca2fbc89fdf7/playground/data/coco2014_val_qa_eval).
