### ISSUE TITLE
复现RL训练时报错

### ISSUE THREAD

**Issue by Mr-Loevan** [llava-rlhf/LLaVA-RLHF#22]
```
Traceback (most recent call last):
  File "/mnt/workspace/wenyi/LLaVA-RLHF/RLHF/finetune_lora_ppo.py", line 560, in <module>
    train()
  File "/mnt/workspace/wenyi/LLaVA-RLHF/RLHF/finetune_lora_ppo.py", line 552, in train
    trainer.train(
  File "/mnt/workspace/wenyi/LLaVA-RLHF/RLHF/models/rl_trainer.py", line 324, in train
    self.log_history.append(self.step(infinite_train_dataloader, step_idx))
  File "/mnt/workspace/wenyi/LLaVA-RLHF/RLHF/models/rl_trainer.py", line 250, in step
    train_stats = self.step_with_rollouts(rollouts)
  File "/mnt/workspace/wenyi/LLaVA-RLHF/RLHF/models/rl_trainer.py", line 224, in step_with_rollouts
    value_loss, value_stats = self.compute_value_loss(rollouts_batch)
  File "/mnt/workspace/wenyi/LLaVA-RLHF/RLHF/models/ppo_trainer.py", line 725, in compute_value_loss
    outputs = self.policy(
  File "/opt/conda/envs/llava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/envs/llava/lib/python3.10/site-packages/accelerate/utils/operations.py", line 553, in forward
    return model_forward(*args, **kwargs)
  File "/opt/conda/envs/llava/lib/python3.10/site-packages/accelerate/utils/operations.py", line 541, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "/opt/conda/envs/llava/lib/python3.10/site-packages/torch/amp/autocast_mode.py", line 14, in decorate_autocast
    return func(*args, **kwargs)
  File "/opt/conda/envs/llava/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1139, in forward
    if torch.is_grad_enabled() and self.reducer._rebuild_buckets():
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`, and by 
making sure all `forward` function outputs participate in calculating loss. 
If you already have done the above, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).
Parameter indices which did not receive grad for rank 0: 1120 1121
 In addition, you can set the environment variable TORCH_DISTRIBUTED_DEBUG to either INFO or DETAIL to print out information about which particular parameters did not receive gradient on this rank as part of this error
```
启动rl的训练时，碰到了这个问题，请问是什么情况。

**Comment by LiqiangJing** [comment]
Hi, 
I also met the same problem. Did you fix this issue?

**Comment by Mr-Loevan** [comment]
@Shengcao-Cao could you please help fix this issue？

**Comment by Edward-Sun** [comment]
Hi @LiqiangJing @Mr-Loevan, did you modify the modeling code in the code base? The error comes from where some parameters in the model are not used in the forward pass, but we have made sure that would not happen in our code.

**Comment by linjieli222** [comment]
Also met the same error, and did not modify the modeling code. 

Tried to get more detailed info with `TORCH_DISTRIBUTED_DEBUG=INFO`, which prints out 
`Parameters which did not receive grad for rank 0: value_model.value_head.bias, value_model.value_head.weight
Parameter indices which did not receive grad for rank 0: 896 897`

Any ideas why?

**Comment by HarrySSH** [comment]
what's your batch size? I get that same error when my total batch size is very small. My issue is gone when I used a bigger batch size.

**Comment by hxhcreate** [comment]
Get the same error

**Comment by UestcJay** [comment]
> what's your batch size? I get that same error when my total batch size is very small. My issue is gone when I used a bigger batch size.

I use a 80GA100， get that same error.  what's your batch size?

**Comment by UestcJay** [comment]
> Get the same error

do you solve the problem?

**Comment by UestcJay** [comment]
> do you solve the problem?

do you solve the problem?

**Comment by GasolSun36** [comment]
same problem, any solusions?

**Comment by zhyang2226** [comment]
Hi, everyone! I encountered the same issue, and I believe it can be resolved using the following approach:

Navigate to the file named "rl_models.py" and locate line 305. The original code for the dummy loss in the "policy" forward pass is written as:

> if "lora_value" in key:  
 
You should modify it to include "value_head" as well:

> if "lora_value" in key or "value_head" in key:  
 
The error isn't associated with the computation of the value loss. Instead, it arises from the failure to utilize all parameters with ''requires_grad=True'' during the forward pass for the policy loss calculation.

**Comment by Edward-Sun** [comment]
> if "lora_value" in key or "value_head" in key:

Amazing! Thank a lot @zhyang2226! It's always safe to use more paramters in the dummy loss. Though, I heard lots of people could succesfully use our codebase and didn't encouter any problem, so I thought it was some environment mismatch issue. Finally the issue can be closed!

cc @Mr-Loevan @LiqiangJing @linjieli222 @hxhcreate @UestcJay @GasolSun36
