### ISSUE TITLE
The accuracy of reward model seem to be low

### ISSUE THREAD

**Issue by Wizardcoast** [llava-rlhf/LLaVA-RLHF#24]
Thanks for sharing you excellent research.
I'm training a full-finetuned reward model (without QLora) from "LLaVA-RLHF-13b-v1.5-336/sft_model" with LLaVA-Human-Preference-10K, and find the eval accuracy is around 63%-67%. This seems to be under expected as on NLP datasets the reward accuracy may around 75%.
Is this performance ehough for the RLHF pipeline or any intuition to revise this？

**Comment by Edward-Sun** [comment]
Hi, this is enough. According to [alpacafarm](https://arxiv.org/abs/2305.14387) and our internal study, the held-out human agreement rate is typically also around 65 - 70%.

Similar issue: https://github.com/llava-rlhf/LLaVA-RLHF/issues/16
