### ISSUE TITLE
NotImplementedError in rl_trainer.py

### ISSUE THREAD

**Issue by janak11111** [llava-rlhf/LLaVA-RLHF#25]
**Got Error NotImplementedError in rl_trainer.py during PPO Finetuning for Evaluate Function**  

steps:   2%|███▍                                                                                                                                                                                                       | 4/236 [02:00<1:56:08, 30.04s/it]
Traceback (most recent call last):
  File "/LOCAL_PATH/LLaVA-RLHF/RLHF/finetune_lora_ppo.py", line 560, in <module>
    train()
  File "/LOCAL_PATH/LLaVA-RLHF/RLHF/finetune_lora_ppo.py", line 552, in train
    trainer.train(
  File "/LOCAL_PATH/LLaVA-RLHF/RLHF/models/rl_trainer.py", line 323, in train
    self.evaluate(step_idx)
  File "/LOCAL_PATH/miniconda3/envs/llava_rlhf/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/LOCAL_PATH/LLaVA-RLHF/RLHF/models/rl_trainer.py", line 329, in evaluate
    raise NotImplementedError
NotImplementedError

--------------------------------

**My RL Model Training Script**

#!/bin/bash

set -e
set -x

export CUDA_VISIBLE_DEVICES=0,1
export DATA_DIR="/LOCAL_PATH/data"
export MODEL_DIR="/LOCAL_PATH/LLaVa_checkpoints/llava_lora_checkpoints_1.5_7b"
export PYTHONPATH="$PWD:$PYTHONPATH"
export GPUS_PER_NODE=2
export OMP_NUM_THREADS=1
export TRANSFORMERS_OFFLINE=1

VISION_TOWER=openai/clip-vit-large-patch14-336
BASE_MODEL_NAME=llava_lora_checkpoints_merge

POLICY_LORA=LLaVA-RL-INIT-7b-336-lora-padding/checkpoint-421/lora_default
RM_LORA=LLaVA-Fact-RM-7b-v1.5-336-lora-padding_cosine/checkpoint-1944  # we use early stopping

MODEL_NAME=LLaVA-RL-Fact-RLHF-7b-v1.5-336-lora-padding

LEARNING_RATE=3e-5
KL_COEF=0.1
EPOCH=4
ROLLOUT_BATCH_SIZE=8
STEP_BATCH_SIZE=8
ROLLOUT_PER_DEVICE_BATCH_SIZE=4
REWARD_MODEL_PER_DEVICE_BATCH_SIZE=4
STEP_PER_DEVICE_BATCH_SIZE=4
NOPTEPOCHS=2

INCOMPLETE_RESPONSE=-8.0
LENGTH_BONUS=-10.0
CORRECT_BONUS=2.0

torchrun \
    --standalone \
    --nnodes=1 \
    --nproc-per-node=$GPUS_PER_NODE \
    /LOCAL_PATH/LLaVA-RLHF/RLHF/finetune_lora_ppo.py \
    --do_train \
    --seed 42 \
    --step_batch_size $STEP_BATCH_SIZE \
    --step_per_device_batch_size $STEP_PER_DEVICE_BATCH_SIZE \
    --rollout_batch_size $ROLLOUT_BATCH_SIZE \
    --rollout_per_device_batch_size $ROLLOUT_PER_DEVICE_BATCH_SIZE \
    --reward_model_per_device_batch_size $REWARD_MODEL_PER_DEVICE_BATCH_SIZE \
    --base_model_name $MODEL_DIR/$BASE_MODEL_NAME \
    --policy_model_name_or_path $MODEL_DIR/$POLICY_LORA \
    --reward_model_name_or_path $MODEL_DIR/$RM_LORA \
    --learning_rate $LEARNING_RATE \
    --init_value_with_reward True \
    --warmup_steps 5 \
    --dataset_path $DATA_DIR/train_data_latest.json \
    --train_splits "train" \
    --output_dir $MODEL_DIR/$MODEL_NAME \
    --total_epochs $EPOCH \
    --group_by_length False \
    --evaluation_strategy "steps" \
    --evaluation_steps 50 \
    --save_strategy "steps" \
    --save_steps 100 \
    --save_total_limit 3 \
    --weight_decay 0.0 \
    --lr_scheduler_type "cosine" \
    --logging_steps 5 \
    --report_to "wandb" \
    --ddp_backend "nccl" \
    --bf16 True \
    --penalty_reward_value $INCOMPLETE_RESPONSE \
    --length_bonus_score $LENGTH_BONUS \
    --correct_bonus_score $CORRECT_BONUS \
    --relative_stop_token_penalty True \
    --penalize_no_stop_token True \
    --ddp_find_unused_parameters False \
    --resume_from_training True \
    --kl_coef $KL_COEF \
    --max_grad_norm 1.0 \
    --whitening_async_stats "full_batch" \
    --clean_tokens_after_eos True \
    --temperature 1.0 \
    --whiten_rewards False \
    --model_max_length 2048 \
    --query_len 128 \
    --response_len 896 \
    --noptepochs $NOPTEPOCHS \
    --image_folder /LOCAL_PATH/playground/data/QA_images \
    --vision_tower $VISION_TOWER \
    --mm_vision_select_layer -2 \
    --mm_use_im_start_end False \
    --mm_use_im_patch_token False \
    --freeze_mm_mlp_adapter True \
    --reward_prompt_file /LOCAL_PATH/LLaVA-RLHF/RLHF/prompts/reward_prompt.txt \
    --image_aspect_ratio 'pad'

**Evaluate Function Not implemented yet ?**

**How to resolve this?**

Thanks.

**Comment by Edward-Sun** [comment]
Hi @janak11111 , we don't do evaluation during the RL process. Please use our original configuration of `--evaluation_strategy "no"`
