### ISSUE TITLE
Question About the reward model

### ISSUE THREAD

**Issue by tyxiong23** [llava-rlhf/LLaVA-RLHF#32]
Hi authors, I am trying to use your pretrained reward model to score the training pair-wise data of LLaVA-RLHF.
However, the probability that the reward model gives higher score to the chosen response is only 52%, and the average score of chosen responses is only 0.0001 higher.
![img_v3_02d3_b8f5dfc1-1113-4434-989e-be20bea476ch](https://github.com/user-attachments/assets/b0604d37-0d1b-42bf-b73c-0f7219fe8b5c)

The score that the reward model predict is usually around -0.15.

I wonder if I made a mistake here. Below is how I load and use your model.
<img width="773" alt="image" src="https://github.com/user-attachments/assets/acbdfb92-e0f7-44cf-8a4f-d917ad92fc15">

I also use 'pad' to preprocess the input image. Thanks a lot for your kind help

**Comment by Edward-Sun** [comment]
Through private communication, @tyxiong23 found this is due to the mis-proper installation of the llava library (right?).

**Comment by tyxiong23** [comment]
> Through private communication, @tyxiong23 found this is due to the mis-proper installation of the llava library (right?).

Yeah, this is due to improper installation of llava library, as well as the mis-alignment in input format. Thanks for your kind help.
