### ISSUE TITLE
Images for the SFT dataset

### ISSUE THREAD

**Issue by yuvalkirstain** [llava-rlhf/LLaVA-RLHF#4]
Hey, in the [link ](https://huggingface.co/datasets/shengs/LLaVA-SFT-122K) to the sft dataset we can see the conversation and image id, but it is unclear to me where can I download the images. I will appreciate clarification on the manner. Thank you.

**Comment by Edward-Sun** [comment]
Hi, you can download the COCO images here: https://cocodataset.org/#download

The flicker images can be found here: https://drive.google.com/file/d/1CNLu1zJKPtliQEYCZlZ8ykH00ppInnyN/view

**Comment by sIncerass** [comment]
Hi @yuvalkirstain, thanks for your interests. 
The flicker images can be found here: https://huggingface.co/datasets/s-lab/images/blob/main/images.tar.gz.
