### ISSUE TITLE
Any simple script to run this model using llava? (help)

### ISSUE THREAD

**Issue by barshag** [llava-rlhf/LLaVA-RLHF#5]
Assume  I got all the llava code + downloaded the model.

 How do I run this model giving Image+Text.
Any full-script that doing this will be awesome!

**Comment by Edward-Sun** [comment]
Hi, to simplify the modifications, we just added a minimal example to launch the llava-rlhf demo. Please let me know if [this](https://github.com/llava-rlhf/LLaVA-RLHF/tree/main/demo) works for you.
